### ISSUE TITLE
Border Arrow Too Thin, Making It Difficult to Locate

### ISSUE THREAD

**Issue by mariop64** [WindowTop/WindowTop-App#317] opened 2023-09-08 13:19 UTC
Request a thicker option be available or a slider that allows the user to decide on the thickness of the arrow this version is too thin and I often find myself struggling to find it. This is especially apparent on larger monitors, or ones with special aspect ratios like Ultrawide monitors 21:9 or 32:9
![image](https://github.com/WindowTop/WindowTop-App/assets/31108587/84c10e06-4a41-48b6-b46d-3c453dde1655)

**Comment by Mystqr4** [comment] 2023-09-09 05:56
I wonder if a slider in the settings to adjust the thickness will be a great idea. Good request!

I don't know if you have experienced it also but on random occasions I have experienced erratic flashing of the bar on hover. It doesn't always happen but does on an occasion.

**Comment by mariop64** [comment] 2023-09-09 12:51
I have experienced that as well yes, there is some inconsistency issue when you hover near the arrow and perhaps there is a better way than using a slider for the previous issue.

**Comment by gileli121** [comment] 2023-09-09 21:50
@mariop64 @Mystqr4 
Thanks for the report.
I have experienced it also, but not in 5.22-beta6 yet.
Can you please try beta 6 from here?

https://github.com/WindowTop/WindowTop-App/issues/313#issuecomment-1712645441

I fixed many issues, and it may fix some bugs like this.
Let me know if you reproduce it using this version.

About the suggestion, it sounds like a good idea.
I may add it.

Thanks.

**Comment by gileli121** [comment] 2023-09-09 23:45
I found a regression from beta 6 using @Mystqr4 configuration.. the app failed to start as an admin user if it was configured to start as an admin user.

It is fixed in beta 7.

Download from here

https://github.com/WindowTop/WindowTop-App/issues/313#issuecomment-1712663166

**Comment by Mystqr4** [comment] 2023-09-11 09:19
> @mariop64 @Mystqr4 Thanks for the report. I have experienced it also, but not in 5.22-beta6 yet. Can you please try beta 6 from here?
> 
> [#313 (comment)](https://github.com/WindowTop/WindowTop-App/issues/313#issuecomment-1712645441)
> 
> I fixed many issues, and it may fix some bugs like this. Let me know if you reproduce it using this version.
> 
> About the suggestion, it sounds like a good idea. I may add it.
> 
> Thanks.

On first attempt the flashing happened again right after the beta 8 version update. It doesn't happen often so I will have to keep an eye on it and report back if it happens again.

Any thoughts on the ability to be able to change the thickness of the little hover arrow to make it more visible for people with larger screens and different aspect ratios. It's perfect right now for me but I am predominantly using a laptop so its fine for me but I think @mariop64 idea is a pretty good one.

**Comment by gileli121** [comment] 2023-09-11 19:20
This is a good idea. But I am not sure to include it as part of 5.22
Maybe 5.23
Because the work that I invested in 5.22 is already huge and I want to finish the release.
The reason that I consider including it is because it should be a very easy feature.

About the flashing issue, I consider it a bug so it has higher priority.
I will probably try to fix it as part of 5.22

I suspect you can reproduce the bug after changing the monitor's DPI scaling.
A lot of bugs are originated from DPI.

**Comment by gileli121** [comment] 2024-11-26 22:20
@mariop64 @mariop64  
I started working on it and completed part of the implementation today.  
Here's how it looks with an increased arrow width:  

![image](https://github.com/user-attachments/assets/a92c464f-5945-4207-9e17-dcd2bfcaae93)  

I plan to continue working on it next Thursday or Sunday next week
The only remaining task is implementing the settings to control the value.

**Comment by gileli121** [comment] 2024-12-03 22:35
Today, I finished implementing the part for adjusting settings, saving them, and loading them for the arrow.  

Here is a screenshot:  
![image](https://github.com/user-attachments/assets/4dde187c-be22-4b64-890d-c78b807dfbe8)  

There’s still some work to do.  
This is just the first iteration, and I haven’t released a version yet.

**Comment by gileli121** [comment] 2024-12-08 23:46
Released in [5.26](https://github.com/WindowTop/WindowTop-App/releases/tag/5.26)

### New Option to Adjust Toolbar Arrow Thickness! (#317)  

You can now adjust the thickness of the toolbar arrow using this new option:  
![image](https://github.com/user-attachments/assets/bd1e4af7-d7ba-4f5f-8460-9a80d2fbbaf1)  

For example, before and after adjusting from 100% to 400%:  
![image](https://github.com/user-attachments/assets/8f5f2ed7-3461-47e7-a7d1-2cd1a41ac1c1)

**Comment by mariop64** [comment] 2024-12-09 04:01
Changing the default color to be green was also a good move, I messed around with the beta version, great addition!

**Closed** 2024-12-22 19:36 UTC
Labels: enhancement, in-progress, testing..., UsersCount-2
