### ISSUE TITLE
This update reset all my settings. bar 2 but it still shows them as being set. 

### ISSUE THREAD

**Issue by EoinBurke93** [WindowTop/WindowTop-App#297] opened 2023-05-25 06:00 UTC
The only settings still in effect (that were at least very noticeable); are live preview (and I'm sure that was a default one) & show mouse preview on hover.
I had changed most settings (about half), including a lot of the Hotkeys, but going back to change them, they also showed the previous settings.

An app restart, PC restart or reinstallation didn't work, but uninstalling the Windows version, and then installing the ordinary version worked (because they have different settings folders is what I'm thinking)

I don't have the Windows app versions of the settings files anymore, in clearing all traces of it to fix this app, so I can't upload them unfortunately. I also can't copy them into my ordinary install either (if they were the same, but I doubt it. Maybe Windows apps use a cache or something that wouldn't clear on a reinstall. But that's a blind guess. You're the developer.

Let me know if I can help with any more information. But remember I have no trace of the problematic Windows version of the app anymore and just using the ordinary version with totally new config files. I do know for sure that it happened after I restarted the app after I downloaded an update.
I use your app constantly and I knew straight away all my settings were reset after the update restart and that the app said they were fine.

**Comment by gileli121** [comment] 2023-05-25 06:17
@EoinBurke93 
Thanks for the report, I will check it now...
I am surprised that it happened.

Do you know what version you had before?
From where did you install the app? Microsoft store or from the installer?
Please note that if you install the update via the installer while the app is installed from the Microsoft Store, it will look like the settings will reset, but in fact, it is just another version that stores the settings in another place

Other than the settings reset issue, the app work file?


I will change it so that in such a case it will create a backup file of the settings file.
Will be released as a hotfix.

**Comment by EoinBurke93** [comment] 2023-05-25 12:37
One thing I did set in your settings.json manually was default preview size
as your defaults don't take 4k monitors into account. I always set PIP to
about 1/5th of my screen, but your max default was way too small on a 4k
monitor. I can't tell you what dimensions I set as I lost the setting, but
that ratio was Ideal. So one improvement, besides settings backup would be
to increase the default PIP resolution options.
Perhaps this is why the update reverted to default? I don't know what your
checks are, but gnome extensions did this often. It wouldn't explain the
non responsive toggles though (they did switch, just not change settings)

Feature wise, PIP, Set top and Anchors for the win! Preview on hover and
click though should be default in my opinion, but I just got used to that
in Gnome and that's the only reason I'd use them; Minify a vm or app, set
it to top and be able to actually work with the window all with one flick
of the mouse. Then set top should have been a windows shortcut all along,
plus anchors for larger apps also set with a differnt flick or keyboard
shortcut. These things are why I refused to use windows for years.

Complement time:
This app, wox, buying a mouse with gestures, windows powertoys, and a
decent terminal fixed almost everything I hated about windows and I can't
thank you enough for fixing a ton of my issues at once as
researching replacements for every gripe I had was a pain. And no PIP
program comes close to yours. I was so stubborn with OpenSuse for 12 years
before this allowed me to finally switch.
It's perfect when you have to use a lot of VMs (one OS version for when
each program was commissioned dating back to the 80s crap that you see if
you ever worked for an old company in IT). I had a similar setup though
extensions in Gnome DE and when I switched back to windows for work, I
needed the same functionality and this does everything and without manually
editing files to make them compatible with upgrades every 6 months and
editing settings files for basic extensions.

**Comment by gileli121** [comment] 2023-05-25 13:08
@EoinBurke93 
Thank you very much for your feedback and I am happy to hear that the help really helps you and is great for you.
Can you please copy-paste your great feedback into Microsoft store reviews?
Here you can submit a review:
ms-windows-store://review/?ProductId=9PG6GHB4CT57

Copy and paste this link into the browser. it will open the MS Store app with a prompt to provide your feedback

And thanks for purchasing. You don't have to (only if you care to use the downloadable version but it is the same as the store one)

About your other suggestions, I noted them and will think about them when I will work on v5.21

**Comment by gileli121** [comment] 2023-05-26 21:25
I am closing for now since this is probably not a bug, but some accident by switching between the MS store and the downloadable version.
If you think that it should be reopened or you reproduced it again, let me know.

**Closed by gileli121** 2023-05-26 21:25 UTC
