### ISSUE TITLE
The product key always expires after being cleaned by computer cleaning software

### ISSUE THREAD

**Issue by chenchen100** [WindowTop/WindowTop-App#339] opened 2023-12-15 08:53 UTC
I‘m not sure which cleanner causing all of this
I don't know where the key is saved, is it in the registry? When I run the cleaning software, the key will disappear and I need to inject it again

The cleaning software I use includes Advanced SystemCare and Lenovo Computer Manager，I guess it's the former.

I'm not sure if it's his fault, but every time I run the cleanup, the next time it starts, he will pop up asking for a key input

Perhaps the storage location of the key needs to be changed
![image](https://github.com/WindowTop/WindowTop-App/assets/95748110/47733543-d8fa-41fb-8184-ccf904ad1050)
![image](https://github.com/WindowTop/WindowTop-App/assets/95748110/ec436c40-2f09-4546-936d-ee236a24cac9)
![image](https://github.com/WindowTop/WindowTop-App/assets/95748110/0bf6af90-087c-4a75-8623-d1eca0be6f4e)

**Comment by gileli121** [comment] 2023-12-15 13:47
@chenchen100 

Please check if the cleaner removes in %AppData% the WindowTop folder or the files inside.
If it does, this explains the problem, and you will have somehow to exclude it from the cleaner.

The folder is located at %AppData%\WindowTop

Type it in the file explorer address and press enter
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/51589478-c777-46f6-b6ce-d54463ab987f)

It will bring you here (in my case, it is under my username)
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/2c7cedc9-2b7b-440d-8068-85029f937448)


Let me know if these files and folders deleted after cleaning.

**Comment by chenchen100** [comment] 2023-12-17 06:30
@gileli121 
I tried it, But to my surprise, it didn't disappear after I cleaned it up, both of two cleanner.
I'm a bit confused now, is it that the only device identifier has changed? It once popped up a prompt asking me if I wanted to activate on this device, which only happened once. But I only activated it on this computer, and the activation code was purchased through legitimate channels. How could this be possible?
Anyway, I will continue to investigate. Thank you for your concern and reply. If I find any clues, I will continue to reply on this issue.
![image](https://github.com/WindowTop/WindowTop-App/assets/95748110/8d43b7d7-9efb-45b9-881e-8b55fba58944)
![image](https://github.com/WindowTop/WindowTop-App/assets/95748110/e3737893-39d0-42cf-a0fe-b01a9abef970)
If you need any information, I will cooperate with you to help you troubleshoot the problem

**Comment by gileli121** [comment] 2023-12-17 07:48
@chenchen100 
This makes sense much better.
The `ComputerId` property may change if advanced systemcare updates like BIOS or firmware.
However, updating BIOS or firmware should not happen every time and should be rare.
Are you sure that after each cleanup, the  `ComputerId` value changed?

In the worst case, the app will ask you to reset the key (unregister other computer IDs) so it will not block you.
I am working on https://github.com/WindowTop/WindowTop-App/issues/332 that will help to handle this problem

**Comment by chenchen100** [comment] 2023-12-25 02:01
When I started my computer today, it popped up
![image](https://github.com/WindowTop/WindowTop-App/assets/95748110/34d050ec-dac1-47a0-8f06-b508bd81a9ed)
settings.json info:
![image](https://github.com/WindowTop/WindowTop-App/assets/95748110/b14cdd17-7ee2-4d6e-99f8-cf8bd376290f)
Computer startup time：
![image](https://github.com/WindowTop/WindowTop-App/assets/95748110/c0e10982-f101-4db6-a009-4c18c183b7bd)

The computer networking time I found is
====Start time: [2023/12/25 周一  9:44:00.62]====  
dr1004({"result":"1","msg":"\u8ba4\u8bc1\u6210\u529f"}) 
====End time: [2023/12/25 周一  9:44:00.81]====  

Can this indicate that the computer was not connected to the internet when the program queried whether the key was valid, resulting in the key becoming invalid?

For Your Information.

**Comment by gileli121** [comment] 2023-12-25 20:14
@chenchen100 
I checked the code again, and it should not disable the license even if it fails to validate it.
If you see such an error, the app should continue to run unlocked.
But this error should be fixed anyway. It should avoid checking if there is no internet.

Are you saying that after the error, the license was disabled?
Do you use the Microsoft Store version? Or do you install it via the regular installer?

If this is the case, I will need logs from you.


1. Download this file:
[NLog.zip](https://github.com/WindowTop/WindowTop-App/files/8247871/NLog.zip)
2. Extract from there the file `NLog.config`
3. Put the `NLog.config` in `C:\Program Files\WindowTop`
4. Start WindowTop 
5. Reproduce the problem, and right after you get the error, exit the app
6. Go to `%appdata%/windowtop`
7. Send me the file `WindowTopLog.log` that was created there.


Thanks.

**Comment by chenchen100** [comment] 2023-12-27 01:47
I am using the Microsoft Store version, but I have downloaded it again
This may take a few days

**Comment by chenchen100** [comment] 2024-01-07 01:34
It finally appeared
[WindowTopLog.log](https://github.com/WindowTop/WindowTop-App/files/13851864/WindowTopLog.log)

**Comment by gileli121** [comment] 2024-01-07 21:15
@chenchen100 
Thank you.
From the logs, what happened is very clear.

It tried to validate the key on the server and got an unexpected response that contained something that may suggest that something on your network blocked the connection.

It prints this response:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta id="viewport" name="viewport" content="target-densitydpi=device-dpi,width=640px,user-scalable=1">
<meta name="renderer" content="webkit" />
<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE">
<title>????????</title> 
<!--Dr.COMWebLoginID_0.htm-->

<script type="text/javascript">
sv=0;sv1=0;v6='http://ip6.login.hnust.cn:9002/v6                       ';myv6ip='                                       ';v4serip='192.168.254.226';m46=0;v46ip='10.152.134.177'                         ;
vid=0   ;mip=010152134177;Gno=0000;vlanid="0"   ;AC="";                          ipm="c0a8fee2";ss1="0010f368ae15";ss2="0000";ss3="0a9886b1";ss4="000000000000";ss5="10.152.134.177" ;ss6="192.168.254.226";timet=1704590392; 
osele=0;//1=??????
domain='ip6.login.hnust.cn';// //////////////////////////
zxopt=0;//1??????8???(??201606??????)
hidm=0,hidn=0;/////
aolno=46915;//////
wopt=0;
eport=-1,eclass=1;//
</script>

<script type="text/javascript">
```

It can't be something from the windowtop server.
I checked it.

I see some stuff like `http://ip6.login.hnust.cn:9002/v6`, `COMWebLoginID_3` , `@telecom`, `@unicom`, `@cmcc`

Do you recognize any of this?
It does not give any room to question how it got such an unexpected response.
Something in your network interrupted the request and returned this instead.

Could you check it?

Anyway, WindowTop should still be able to handle such an event by ignoring this response and not identifying it as a response that tells that the key is invalid. 

This is a bug, for sure.

I will work on fixing it and provide you with a version to check

**Comment by gileli121** [comment] 2024-01-07 22:21
@chenchen100 
Please check this version
https://github.com/WindowTop/WindowTop-App/releases/download/v5.22.5/WindowTop.5.22.6-beta1.-.setup.exe

It includes a fix for this problem.

Please give it a try for a few days and let me know if the issue is fixed.
Thank you.

**Comment by chenchen100** [comment] 2024-01-24 09:11
Some WiFi devices require additional authentication methods in addition to entering the connection and password. For example, when accessing the network, they will be redirected to the login page (without login). They need to enter the account and password for access before submitting to log in. I guess the program should have been redirected to the login page while accessing the network, and in reality, it cannot connect to the network

**Comment by chenchen100** [comment] 2024-01-24 09:13
> Some WiFi devices require additional authentication methods in addition to entering the connection and password. 

I won't be able to return to that place (due to network conditions) for at least a month, so I won't be able to test if the program works

**Comment by chenchen100** [comment] 2024-01-24 09:19
> For example, when accessing the network, they will be redirected to the login page (without login). They need to enter the account and password for access before submitting to log in. 

That is to say, it may depend on the order in which the program runs. If the program runs before I log in to WiFi (I wrote a VBS script to automatically log in), it will report an error.

**Comment by gileli121** [comment] 2024-01-25 19:15
@chenchen100 
I see.
Thanks for the information.
I will check what to do to fix it

**Closed** 2024-03-30 15:00 UTC
Labels: bug, fixed, testing...
